### ISSUE TITLE
Set up xUnit Tests to be run by Travis and Appveyor

### ISSUE THREAD

**Issue by Mafii** [IDPA-2016-NEAT-CNN/NEAT_Visualizer#22]
@STJEREM can you please look into this?

**Comment by Mafii** [comment]
Please do it on this branch: https://github.com/IDPA-2016-NEAT-CNN/NEAT_Visualizer/tree/Add_xUnit

**Comment by STJEREM** [comment]
I will install mono and fix it tomorrow.
